paths:
  episodic_db: "memory/mind.db"
  semantic_db: "memory/semantic.db"

models:
  subconscious:
    model_name: "EleutherAI/gpt-neo-2.7B"
    torch_dtype: "float16"  # Required for larger models
    device_map: "auto"      # Helps with memory management
  conscious:
    refinement_model: "facebook/bart-large"
    embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

thresholds:
  salience: 0.35
  novelty: 0.25
  relevance: 0.3
  duplicate: 0.85